import { Router } from "express";

import bankAccountRoutes from "./bankAccountRoutes.js";
import bankRoutes from "./bankRoutes.js";
import bankNumberRoutes from "./bankNumberRoutes.js";
import paymentsByProviderRoutes from "./paymentsByProviderRoutes.js";
import branchRoutes from "./branchRoutes.js";
import brandRoutes from "./brandRoutes.js";
import budgetRoutes from "./budgetRoutes.js";
import cashPaymentRoutes from "./cashPaymentRoutes.js";
import chatRoutes from "./chatRoutes.js";
import categoryRoutes from "./categoryRoutes.js";
import companyRoutes from "./companyRoutes.js";
import countryRoutes from "./countryRoutes.js";
import dashboardRoutes from "./dashboardRoutes.js";
import departmentRoutes from "./departmentRoutes.js";
import expenseConceptCategoryRoutes from "./expenseConceptCategoryRoutes.js";
import expenseConceptRoutes from "./expenseConceptRoutes.js";
import expenseConceptBudgetRoutes from "./expenseConceptBudgetRoutes.js";
import importedInvoicesRoutes from "./importedInvoicesRoutes.js";
import invoicesPackageCompanyRoutes from "./invoicesPackpageCompanyRoutes.js";
import invoicesPackageRoutes from "./invoicesPackpageRoutes.js";
import logImportBankMovementsRoutes from "./logImportBankMovementsRoutes.js";
import moduleRoutes from "./moduleRoutes.js";
import municipalityRoutes from "./municipalityRoutes.js";
import pageRoutes from "./pageRoutes.js";
import providerRoutes from "./providerRoutes.js";
import roleRoutes from "./roleRoutes.js";
import routeRoutes from "./routeRoutes.js";
import roleVisibilityRoutes from "./roleVisibilityRoutes.js";
import stateRoutes from "./stateRoutes.js";
import structureRoutes from "./structureRoutes.js";
import userRoutes from "./userRoutes.js";
import authorizationFolioRoutes from "./authorizationFolioRoutes.js";
import scheduledPaymentRoutes from "./scheduledPaymentRoutes.js";
import bankMovementRoutes from "./bankMovementRoutes.js";
import conciliacionRoutes from "./conciliacionRoutes.js";
import fixIndexesRoutes from "./fixIndexesRoutes.js";

const router = Router();

router.use("/users", userRoutes);
router.use("/roles", roleRoutes);
router.use("/pages", pageRoutes);
router.use("/modules", moduleRoutes);
router.use("/companies", companyRoutes);
router.use("/brands", brandRoutes);
router.use("/branches", branchRoutes);
router.use("/budget", budgetRoutes);
router.use("/chat", chatRoutes);
router.use("/categories", categoryRoutes);
router.use("/countries", countryRoutes);
router.use("/states", stateRoutes);
router.use("/municipalities", municipalityRoutes);
router.use("/expense-concept-categories", expenseConceptCategoryRoutes);
router.use("/expense-concept", expenseConceptRoutes);
router.use("/expense-concept-budget", expenseConceptBudgetRoutes);
router.use("/providers", providerRoutes);
router.use("/departments", departmentRoutes);
router.use("/banks", bankRoutes);
router.use("/bank-accounts", bankAccountRoutes);
router.use("/bank-numbers", bankNumberRoutes);
router.use("/payments-by-provider", paymentsByProviderRoutes);
router.use("/imported-invoices", importedInvoicesRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/invoices-package", invoicesPackageRoutes);
router.use("/invoices-package-company", invoicesPackageCompanyRoutes);
router.use("/log-import-bank-movements", logImportBankMovementsRoutes);
router.use("/role-visibility", roleVisibilityRoutes);
router.use("/cash-payments", cashPaymentRoutes);
router.use("/authorization-folios", authorizationFolioRoutes);
router.use("/scheduled-payments", scheduledPaymentRoutes);
router.use("/routes", routeRoutes);
router.use("/structure", structureRoutes);
router.use("/bank-movements", bankMovementRoutes);
router.use("/conciliacion", conciliacionRoutes);
router.use("/fix", fixIndexesRoutes);

export default router;
