export const userRoles = [
  "SuperAdmin",
  "Admin",
  "Gerente",
  "Revisor",
  "Asistente",
  "Direccion",
  "GerenteFiscal",
  "RevisorFiscal1",
  "PrepagadoFiscal1",
  "PrepagadoFiscal2",
  "PrepagadoFiscal3",
  "RevisorFiscal2",
  "RevisorFiscal3",
  "PrepagadoFiscal4",
];
